sudo: required
language: ruby
services:
- docker
env:
  global:
  - IMAGE_NAME=ringcentral/node
  - secure: PGCVGfP/PmuIO9ugAYdum07Ge/sKdpyuTr7PSrLmrKlrlQJwMgxr1pd/H0l6H7DV2BG2XOvit40pwZtV2VAImBd17jBFMPiemuoiHji01Pm+eEZ7glhw/rpGseg41qfrhZ9aMISPsOBqacoBBn5yRFFqX9iZvWEGmIEVOi0GzpOOoUtM0CRoIcN4bHPH+FMkQr+z/DO9BuTMUBoD+myRa6PM5VhI+lcn6udY4tcdR7JnKrD5P6YS1ISiyNsWEER19zsoA6HFvas1WTvdAfWVkO0Vnpj/8deBBaUVRHbzYFYcxpMy5WOP4g8VovKU9jdnlu3n3zhXtOGqW7jkIUet9DoTuNiI+VeHDHlrLY5hmxvHbvvm1pLkyN5MH4NFbpCCsRDztd2sYhLG6bl9UO0I74T+hVxaRmh+5skNJC8kChTLVAYctu2f446F9QTXEMyzPFnELiWd2qtGhVDQ7vhGjfBeKpLL5QyBH0pIKWEZaPbqrzjqWainNcqU6Kg8XhERdzjZ/9a6MESbqBoSWiqI9VeQ3TJ+cJrNQ/UEOCJ+C8G4e3gJX1CBErgSLyrXqliRBa+GqTA5HQm/2iacVChxawX0sCkUcVUHfAHmwfJl61sgu9X2c3XXTuXrEkumcNa++HhWD3wuC3ACH2MYQ7i6ipryoYXCgSx4TqTn409VcHM=
  - secure: S0S9cfa0l3PuEpWVdaAqvl4xf1dqd6O2mxIAZPbYlz2LZfSMEc2xBq9VqIB6yBDWJZwgOxs+sctTVqhYgsfmnVMw6Ym04UOrqoIZpDspoU9U6O2fzJ+EK1cFwrcjCepKI7kpbEcXDuY69PqKP1QAPVQCtqM1eNPNkU5LKS/HghSY4P7mdz+MOD4egs5XLh0ct2lICQT5TzRISt6mX6eamPDrDxZ5HENdHoPdGDAS/AEwcTGd6XWWWgqpFhIrOMvI7isPm3sxcGPNWRULaz4I7Ngkh3sZ9qX3F8SdiqzJDjVvyMczGqkuObpREFtPZrcphBCZ7NMEI7XNyB7bAf6eU1LTYdjLYIJwEJM2n4clmdqJKJE1GSZ1QPDL35M85vBb5SSGWxRSX3nNJJnM5knCqxpRlSV8sTVghHlkO2d+6XvYsAe8KvGbSU+HCLCa9feLojr75MElvkTAa26P2Feh31KHAq/bWm28HucNjUKGSy36AGwz2co/Ror9XGGpH8uI6T87Ofp1Y8XmxnXb7ulUNGNquQvqoLHDXuJy8vrYqxZSwqtXBMOI+CuFjF+DHcUEtRU446yQesytv4C7cBJB34H9yZI3qYxiwKH+iCgmmt8Oh8DHsElPvu2MK2pRHGL/kXmo4X6pB2lbGWLuUbuVPImrSfX/565/YIB9cPGZFd8=
before_script:
- cd 12
- version="$(awk '/ENV NODE_VERSION/ {print $3}' Dockerfile)"
- base_version="$(awk -F '[:-]' '/FROM/ {print $3}' Dockerfile)"
script:
- docker build -t "$IMAGE_NAME" .
after_script:
- docker images
before_deploy:
- echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}"
- docker tag "$IMAGE_NAME" "${IMAGE_NAME}:${version}-${base_version}"
deploy:
  provider: script
  script: docker push "${IMAGE_NAME}:latest" && docker push "${IMAGE_NAME}:${version}" && docker push "${IMAGE_NAME}:${version}-${base_version}"
  on:
    branch: master
